Repository am32-firmware/AM32, pull requests merged in 2024-11, with the labels that each got.

#27 Add ARK 4IN1
  Inc/targets.h
  Mcu/f051/Src/peripherals.c
Labels: improvement, dont merge, target

#56 Feature/eeprom struct
  Inc/common.h
  Inc/dshot.h
  Inc/eeprom.h
  Inc/signal.h
  Inc/version.h
  Mcu/e230/Inc/IO.h
  Mcu/e230/Inc/eeprom.h
  Mcu/e230/Inc/phaseouts.h
  Mcu/e230/Src/phaseouts.c
  Mcu/f031/Inc/IO.h
  Mcu/f031/Inc/eeprom.h
  Mcu/f031/Inc/phaseouts.h
  Mcu/f031/Src/phaseouts.c
  Mcu/f051/Inc/IO.h
  Mcu/f051/Inc/eeprom.h
  Mcu/f051/Inc/phaseouts.h
  Mcu/f051/Src/phaseouts.c
  Mcu/f415/Inc/IO.h
  Mcu/f415/Inc/eeprom.h
  Mcu/f415/Inc/phaseouts.h
  Mcu/f415/Src/phaseouts.c
  Mcu/f421/Am32.sct
  Mcu/f421/Inc/IO.h
  Mcu/f421/Inc/eeprom.h
  Mcu/f421/Inc/phaseouts.h
  Mcu/f421/Src/phaseouts.c
  Mcu/g071/Inc/eeprom.h
  Mcu/g071/Inc/phaseouts.h
  Mcu/g071/Src/phaseouts.c
  Mcu/g431/Inc/eeprom.h
  Mcu/g431/Inc/phaseouts.h
  Mcu/g431/Src/phaseouts.c
  Mcu/l431/Inc/IO.h
  Mcu/l431/Inc/eeprom.h
  Mcu/l431/Inc/phaseouts.h
  Mcu/l431/Src/phaseouts.c
  Src/dshot.c
  Src/main.c
  Src/signal.c
  Src/sounds.c
Labels: improvement

#101 avoid reset of utility timer
  Mcu/e230/Src/gd32e23x_it.c
  Mcu/e230/Src/peripherals.c
  Mcu/f031/Src/stm32f0xx_it.c
  Mcu/f051/Src/stm32f0xx_it.c
  Mcu/f415/Src/peripherals.c
  Mcu/f421/Src/peripherals.c
  Mcu/g071/Src/stm32g0xx_it.c
  Mcu/g431/Src/peripherals.c
  Mcu/g431/Src/stm32g4xx_it.c
  Mcu/l431/Src/stm32l4xx_it.c
  Src/functions.c
Labels: breaking changes, needs testing
